# Generated by Django 5.2.16 on 2026-10-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctorleave_alter_availabletime_options_and_more'),
        ('services', '0002_modernize_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='specializations',
            field=models.ManyToManyField(blank=True, help_text='Doctor specializations that deliver this service.', related_name='services', to='doctors.specialization'),
        ),
    ]
