# Generated by Django 5.2.16 on 2026-08-11 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_department_appointment_facility_and_more'),
        ('doctors', '0005_doctorleave_alter_availabletime_options_and_more'),
        ('patients', '0003_patient_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('symptoms', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Offered', 'Offered'), ('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], default='Waiting', max_length=10)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entry', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='patients.patient')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='doctors.availabletime')),
            ],
            options={
                'verbose_name_plural': 'waitlist entries',
                'ordering': ['requested_date', 'created_at'],
                'indexes': [models.Index(fields=['doctor', 'requested_date', 'time', 'status'], name='waitlist_slot_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['Waiting', 'Offered'])), fields=('patient', 'doctor', 'time', 'requested_date'), name='unique_open_waitlist_request')],
            },
        ),
    ]
