# Generated by Django 5.2.16 on 2026-08-11 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_backfill_explicit_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('consultation', 'Consultation'), ('procedure', 'Procedure'), ('ward', 'Ward'), ('icu', 'Intensive care'), ('laboratory', 'Laboratory')], default='consultation', max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='operations.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='operations.facility')),
            ],
            options={
                'ordering': ['facility__name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('cleaning', 'Cleaning'), ('out_of_service', 'Out of service')], default='available', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='operations.room')),
            ],
            options={
                'ordering': ['room__number', 'label'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('facility', 'number'), name='unique_room_number_per_facility'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['status'], name='bed_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'label'), name='unique_bed_label_per_room'),
        ),
    ]
