# Generated by Django 5.2.16 on 2026-08-11 03:29

import datetime
import re

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


WEEKDAY_BY_PREFIX = {
    "mon": 0,
    "tue": 1,
    "wed": 2,
    "thu": 3,
    "fri": 4,
    "sat": 5,
    "sun": 6,
}
TIME_PATTERN = re.compile(r"(\d{1,2})(?::(\d{2}))?\s*(am|pm)?", re.IGNORECASE)
WORD_PATTERN = re.compile(r"[a-z]+", re.IGNORECASE)


def parse_weekday(label):
    for word in WORD_PATTERN.findall(label):
        weekday = WEEKDAY_BY_PREFIX.get(word[:3].lower())
        if weekday is not None:
            return weekday
    return None


def parse_times(label):
    found = []
    for hour, minute, meridiem in TIME_PATTERN.findall(label):
        hour = int(hour)
        minute = int(minute or 0)
        meridiem = meridiem.lower()
        if meridiem == "pm" and hour != 12:
            hour += 12
        elif meridiem == "am" and hour == 12:
            hour = 0
        if 0 <= hour <= 23 and 0 <= minute <= 59:
            found.append(datetime.time(hour, minute))
    return found


def structure_legacy_slots(apps, schema_editor):
    """Turn free-text slot names such as ``EVERY SAT 9AM TO 5PM`` into data.

    Anything unparseable keeps the model defaults. Rows that collapse onto the
    same (weekday, start, end) are merged so the unique constraint that follows
    can be created, with appointments and doctor links repointed to the survivor.
    """
    AvailableTime = apps.get_model("doctors", "AvailableTime")
    Appointment = apps.get_model("appointments", "Appointment")
    Doctor = apps.get_model("doctors", "Doctor")

    canonical = {}
    for slot in AvailableTime.objects.all().order_by("pk"):
        weekday = parse_weekday(slot.name)
        times = parse_times(slot.name)
        if weekday is not None:
            slot.weekday = weekday
        if len(times) >= 2 and times[0] < times[1]:
            slot.start_time, slot.end_time = times[0], times[1]

        key = (slot.weekday, slot.start_time, slot.end_time)
        survivor = canonical.get(key)
        if survivor is None:
            slot.name = (
                f"{dict(WEEKDAY_LABELS)[slot.weekday]} "
                f"{slot.start_time:%H:%M} - {slot.end_time:%H:%M}"
            )
            slot.save(
                update_fields=["name", "weekday", "start_time", "end_time"]
            )
            canonical[key] = slot
            continue

        Appointment.objects.filter(time=slot).update(time=survivor)
        for doctor in Doctor.objects.filter(available_time=slot):
            doctor.available_time.remove(slot)
            doctor.available_time.add(survivor)
        slot.delete()


WEEKDAY_LABELS = [
    (0, "Monday"),
    (1, "Tuesday"),
    (2, "Wednesday"),
    (3, "Thursday"),
    (4, "Friday"),
    (5, "Saturday"),
    (6, "Sunday"),
]


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_modernize_doctor_and_reviews'),
        # structure_legacy_slots repoints appointments onto merged slots.
        ('appointments', '0004_appointment_department_appointment_facility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Requested', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='availabletime',
            options={'ordering': ['weekday', 'start_time']},
        ),
        migrations.AddField(
            model_name='availabletime',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many patients one doctor can see in this slot.'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=5),
        ),
        migrations.RunPython(
            structure_legacy_slots,
            migrations.RunPython.noop,
            elidable=False,
        ),
        migrations.AddConstraint(
            model_name='availabletime',
            constraint=models.UniqueConstraint(fields=('weekday', 'start_time', 'end_time'), name='unique_slot_template'),
        ),
        migrations.AddConstraint(
            model_name='availabletime',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='slot_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='availabletime',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='slot_capacity_at_least_one'),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_doctor_leave', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='doctorleave',
            index=models.Index(fields=['doctor', 'status', 'start_date', 'end_date'], name='leave_doctor_window_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorleave',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_ends_on_or_after_start'),
        ),
    ]
